version: 2.1

jobs:
  build:
    docker:
      - image: "debian:latest"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install build tools and cpputest
          command: 'bash scripts/setup_ci.sh'
      - run:
          name: Library Build
          command: 'mkdir build && cd build && cmake ../ && make -j4 && sudo make install'
      - run:
          name: Package Installation
          command: 'bash scripts/package_install.sh'
      - run:
          name: Scripted Tests
          command: 'cd test_scripts && export SAUROS_HOME="/tmp/.sauros" && python3 run.py ../build/test_app/app'